const { Q, shuffle, R, save, pad } = require('./gen_part1');

// ===================== AI/ML =====================
function genAIML() {
    const S = 'AI / ML'; const all = [];
    const items = [
        { q: 'Supervised learning uses?', c: 'Labeled data', w: ['Unlabeled data', 'No data', 'Random data'], e: 'Supervised learning maps input to known output labels.', d: 'Easy' },
        { q: 'Unsupervised learning is used for?', c: 'Finding hidden patterns without labels', w: ['Predicting known outputs', 'Classification with labels', 'Regression with targets'], e: 'No target variable; discovers structure in data.', d: 'Easy' },
        { q: 'Reinforcement learning learns through?', c: 'Rewards and penalties', w: ['Labeled datasets', 'Clustering', 'Backpropagation only'], e: 'Agent maximizes cumulative reward via trial and error.', d: 'Easy' },
        { q: 'Linear regression predicts?', c: 'Continuous numerical values', w: ['Binary classes', 'Clusters', 'Categories'], e: 'Fits a line to minimize squared errors.', d: 'Easy' },
        { q: 'Logistic regression is used for?', c: 'Binary classification', w: ['Regression', 'Clustering', 'Dimensionality reduction'], e: 'Outputs probability via sigmoid function.', d: 'Easy' },
        { q: 'Decision tree splits data based on?', c: 'Feature that gives best information gain', w: ['Random features', 'All features equally', 'Target variable only'], e: 'Greedy splits maximize purity of child nodes.', d: 'Medium' },
        { q: 'Random forest is?', c: 'Ensemble of decision trees', w: ['Single deep tree', 'Neural network', 'Clustering method'], e: 'Aggregates predictions from multiple trees.', d: 'Easy' },
        { q: 'K-Nearest Neighbors classifies by?', c: 'Majority vote of K nearest points', w: ['Gradient descent', 'Tree splitting', 'Feature elimination'], e: 'Distance-based lazy learner.', d: 'Easy' },
        { q: 'SVM finds?', c: 'Maximum margin hyperplane', w: ['Minimum distance', 'Cluster centers', 'Principal components'], e: 'Support vectors define the decision boundary.', d: 'Medium' },
        { q: 'Naive Bayes assumes?', c: 'Feature independence given class', w: ['All features are correlated', 'No prior probability', 'Linear separability'], e: 'Conditional independence assumption simplifies computation.', d: 'Medium' },
        { q: 'K-Means clustering minimizes?', c: 'Within-cluster sum of squares', w: ['Between-cluster distance', 'Number of features', 'Entropy'], e: 'Iteratively assigns points to nearest centroid.', d: 'Easy' },
        { q: 'Hierarchical clustering produces?', c: 'Dendrogram', w: ['Decision boundary', 'Confusion matrix', 'ROC curve'], e: 'Agglomerative or divisive approach builds tree.', d: 'Medium' },
        { q: 'DBSCAN clusters based on?', c: 'Density of points', w: ['Distance to centroid only', 'Random assignment', 'Feature importance'], e: 'Density-Based Spatial Clustering finds arbitrary shapes.', d: 'Hard' },
        { q: 'Perceptron is?', c: 'Single-layer neural network for linear classification', w: ['Clustering algorithm', 'Regression only', 'Unsupervised method'], e: 'Weighted sum + activation function.', d: 'Easy' },
        { q: 'Backpropagation computes?', c: 'Gradients of loss w.r.t. weights', w: ['Forward pass only', 'Cluster assignments', 'Feature importance'], e: 'Chain rule propagates error backwards through layers.', d: 'Medium' },
        { q: 'Activation function introduces?', c: 'Non-linearity into neural networks', w: ['Linearity', 'Randomness', 'Overfitting'], e: 'Without activation, network is just linear transformation.', d: 'Easy' },
        { q: 'CNN is best for?', c: 'Image recognition tasks', w: ['Sequential text data', 'Tabular data only', 'Audio only'], e: 'Convolutional layers detect spatial patterns.', d: 'Easy' },
        { q: 'RNN is designed for?', c: 'Sequential/time-series data', w: ['Image data', 'Static tabular data', 'Clustering'], e: 'Recurrent connections maintain hidden state across time steps.', d: 'Easy' },
        { q: 'LSTM solves?', c: 'Vanishing gradient in standard RNNs', w: ['Overfitting', 'Underfitting', 'Data imbalance'], e: 'Gates control information flow through memory cell.', d: 'Medium' },
        { q: 'Transformers use?', c: 'Self-attention mechanism', w: ['Recurrent connections', 'Convolutional filters', 'Random forests'], e: 'Attention scores capture relationships regardless of distance.', d: 'Medium' },
        { q: 'Accuracy = ?', c: '(TP+TN) / Total', w: ['TP/FP', 'TP/(TP+FN)', '2*P*R/(P+R)'], e: 'Correct predictions divided by total.', d: 'Easy' },
        { q: 'Precision = ?', c: 'TP / (TP + FP)', w: ['TP / (TP+FN)', '(TP+TN)/Total', 'FP/(FP+TN)'], e: 'Of predicted positives, how many are actually positive.', d: 'Easy' },
        { q: 'Recall = ?', c: 'TP / (TP + FN)', w: ['TP / (TP+FP)', '(TP+TN)/Total', 'FN/(FP+FN)'], e: 'Of actual positives, how many were correctly predicted.', d: 'Easy' },
        { q: 'F1 Score is?', c: 'Harmonic mean of Precision and Recall', w: ['Arithmetic mean', 'Geometric mean', 'Simple average of accuracy'], e: 'F1 = 2*P*R/(P+R), balances precision and recall.', d: 'Medium' },
        { q: 'ROC curve plots?', c: 'True Positive Rate vs False Positive Rate', w: ['Precision vs Recall', 'Accuracy vs Loss', 'Error vs Epochs'], e: 'Shows classifier performance across all thresholds.', d: 'Medium' },
        { q: 'Confusion matrix shows?', c: 'TP, TN, FP, FN counts', w: ['Feature importance', 'Learning rate', 'Cluster assignments'], e: 'Tabulates actual vs predicted classifications.', d: 'Easy' },
        { q: 'Overfitting means?', c: 'Model performs well on training but poorly on test data', w: ['Model fails on both', 'Model is too simple', 'Model has no parameters'], e: 'Model memorizes noise instead of learning patterns.', d: 'Easy' },
        { q: 'Underfitting means?', c: 'Model is too simple to capture patterns', w: ['Model memorizes data', 'Model overfits', 'Perfect generalization'], e: 'High bias, low variance; needs more complexity.', d: 'Easy' },
        { q: 'Cross-validation purpose?', c: 'Assess model generalization on unseen data', w: ['Speed up training', 'Reduce dataset size', 'Increase features'], e: 'K-fold splits data into train/validate partitions.', d: 'Medium' },
        { q: 'Feature scaling is needed because?', c: 'Algorithms sensitive to magnitude perform poorly without it', w: ['It removes features', 'It adds noise', 'It reduces accuracy'], e: 'Normalization/standardization ensures equal feature contribution.', d: 'Easy' },
        { q: 'One-Hot Encoding is used for?', c: 'Converting categorical variables to binary vectors', w: ['Scaling numerical features', 'Removing outliers', 'Reducing dimensions'], e: 'Each category becomes a binary column.', d: 'Easy' },
        { q: 'Label Encoding assigns?', c: 'Integer values to categories', w: ['Binary vectors', 'Random floats', 'String hashes'], e: 'Each unique category gets a unique integer.', d: 'Easy' },
        { q: 'Missing values can be handled by?', c: 'Imputation (mean, median, mode) or deletion', w: ['Ignoring them always', 'Setting all to zero', 'Multiplying by -1'], e: 'Strategy depends on data distribution and missingness pattern.', d: 'Easy' },
        { q: 'Gradient descent minimizes?', c: 'Loss/cost function', w: ['Accuracy', 'Number of features', 'Data size'], e: 'Iteratively updates parameters in direction of steepest descent.', d: 'Medium' },
        { q: 'Learning rate controls?', c: 'Step size in gradient descent', w: ['Number of features', 'Data augmentation', 'Dropout rate'], e: 'Too high: overshoots; too low: slow convergence.', d: 'Medium' },
        { q: 'Regularization reduces?', c: 'Overfitting by penalizing large weights', w: ['Underfitting', 'Training time', 'Dataset size'], e: 'L1/L2 add penalty term to loss function.', d: 'Medium' },
        { q: 'NumPy is used for?', c: 'Numerical array operations', w: ['Web scraping', 'Database queries', 'File compression'], e: 'Efficient multidimensional array computations.', d: 'Easy' },
        { q: 'Pandas provides?', c: 'DataFrame for structured data manipulation', w: ['Image processing', 'Neural network layers', 'GPU computing'], e: 'Tabular data analysis tool in Python.', d: 'Easy' },
        { q: 'Scikit-learn provides?', c: 'Machine learning algorithms and utilities', w: ['Deep learning only', 'Web framework', 'Database ORM'], e: 'Preprocessing, models, metrics all in one library.', d: 'Easy' },
        { q: 'Matplotlib is used for?', c: 'Data visualization and plotting', w: ['Data storage', 'ML training', 'Web development'], e: 'Creates charts, graphs, and visual representations.', d: 'Easy' },
        { q: 'Train-test split typically uses?', c: '80-20 or 70-30 ratio', w: ['50-50 always', '99-1', 'No split needed'], e: 'Majority for training, held-out portion for evaluation.', d: 'Easy' },
        { q: 'Bias in ML refers to?', c: 'Error from oversimplified assumptions', w: ['Error from noise', 'Dataset size', 'Feature count'], e: 'High bias = underfitting the training data.', d: 'Medium' },
        { q: 'Variance in ML refers to?', c: 'Sensitivity to fluctuations in training data', w: ['Average error', 'Constant error', 'Zero error'], e: 'High variance = overfitting to training data.', d: 'Medium' },
        { q: 'Principal Component Analysis (PCA) does?', c: 'Dimensionality reduction', w: ['Classification', 'Clustering', 'Regression'], e: 'Projects data onto directions of maximum variance.', d: 'Medium' },
        { q: 'Dropout in neural networks?', c: 'Randomly deactivates neurons during training', w: ['Adds more neurons', 'Removes layers permanently', 'Speeds up inference'], e: 'Regularization technique preventing co-adaptation.', d: 'Medium' },
        { q: 'Batch normalization does?', c: 'Normalizes layer inputs during training', w: ['Removes all layers', 'Increases batch size', 'Reduces features'], e: 'Stabilizes learning and allows higher learning rates.', d: 'Hard' },
        { q: 'Transfer learning means?', c: 'Using pre-trained model for a new task', w: ['Training from scratch', 'Unsupervised clustering', 'Feature deletion'], e: 'Fine-tune existing model on new domain data.', d: 'Medium' },
        { q: 'Epoch means?', c: 'One complete pass through the entire training dataset', w: ['One batch', 'One sample', 'One layer update'], e: 'Multiple epochs improve learning.', d: 'Easy' },
        { q: 'Batch size is?', c: 'Number of samples processed before updating weights', w: ['Total dataset size', 'Number of features', 'Number of epochs'], e: 'Larger batch = more stable gradient, more memory.', d: 'Easy' },
        { q: 'A* search algorithm uses?', c: 'Heuristic + path cost (f = g + h)', w: ['Only heuristic', 'Only path cost', 'Random selection'], e: 'Combines actual cost and heuristic estimate.', d: 'Medium' },
        { q: 'Minimax algorithm is used for?', c: 'Game playing (adversarial search)', w: ['Regression', 'Clustering', 'Data preprocessing'], e: 'Maximizes own score while minimizing opponent\'s.', d: 'Medium' },
        { q: 'Types of AI include?', c: 'Narrow AI, General AI, Super AI', w: ['Only Narrow AI', 'Only Deep Learning', 'Hardware and Software'], e: 'Classification by capability level.', d: 'Easy' },
        { q: 'Intelligent agent in AI?', c: 'Entity that perceives environment and acts to maximize goals', w: ['Passive data store', 'Simple calculator', 'Static program'], e: 'Agents sense, decide, and act in their environment.', d: 'Easy' },
        { q: 'Knowledge representation in AI uses?', c: 'Logic, semantic networks, frames, ontologies', w: ['Only images', 'Only numbers', 'Only text'], e: 'Structures to encode knowledge for reasoning.', d: 'Medium' },
        { q: 'Polynomial regression fits?', c: 'Curved relationships using polynomial terms', w: ['Only straight lines', 'No relationships', 'Categorical data'], e: 'Transforms features to polynomial degree.', d: 'Medium' },
        { q: 'Multiple regression uses?', c: 'Multiple independent variables to predict one dependent', w: ['One independent variable', 'No variables', 'Only categorical'], e: 'Extends simple linear regression to multiple predictors.', d: 'Easy' },
        { q: 'Ethics in AI includes?', c: 'Bias mitigation, privacy, transparency, accountability', w: ['Only speed optimization', 'Only accuracy', 'Only profit'], e: 'Responsible AI development considers societal impact.', d: 'Easy' },
        { q: 'Data augmentation is?', c: 'Creating modified copies of data to increase dataset size', w: ['Deleting data', 'Reducing features', 'Normalizing only'], e: 'Flips, rotations, crops etc. for image data.', d: 'Medium' },
        { q: 'TensorFlow is?', c: 'Open-source deep learning framework by Google', w: ['Database system', 'Web framework', 'Operating system'], e: 'Enables building and training neural networks at scale.', d: 'Easy' },
    ];
    items.forEach(it => all.push(Q(S, it.q.includes('Regression') ? 'Regression' : it.q.includes('CNN') || it.q.includes('RNN') || it.q.includes('LSTM') ? 'Deep Learning' : it.q.includes('Precision') || it.q.includes('Recall') || it.q.includes('F1') || it.q.includes('ROC') || it.q.includes('Confusion') || it.q.includes('Accuracy') ? 'Evaluation Metrics' : 'ML Basics', it.d, it.q, it.c, it.w, it.e)));
    return all;
}

// ===================== JAVA =====================
function genJava() {
    const S = 'Java'; const all = [];
    const items = [
        { q: 'Java is which type of language?', c: 'Object-Oriented', w: ['Procedural only', 'Functional only', 'Assembly'], e: 'Java follows OOP principles: encapsulation, inheritance, polymorphism, abstraction.', d: 'Easy' },
        { q: 'JVM stands for?', c: 'Java Virtual Machine', w: ['Java Variable Manager', 'Java Version Module', 'Java Visual Maker'], e: 'JVM executes Java bytecode on any platform.', d: 'Easy' },
        { q: 'JDK includes?', c: 'JRE + development tools (compiler, debugger)', w: ['Only JVM', 'Only editor', 'Only libraries'], e: 'JDK is the full development kit.', d: 'Easy' },
        { q: 'JRE includes?', c: 'JVM + core libraries', w: ['Only compiler', 'Only debugger', 'Only source code'], e: 'JRE is needed to run Java applications.', d: 'Easy' },
        { q: 'Encapsulation is achieved by?', c: 'Private fields with public getters/setters', w: ['Public fields', 'Static methods only', 'Abstract classes'], e: 'Data hiding protects internal state.', d: 'Easy' },
        { q: 'Inheritance allows?', c: 'A class to inherit properties of another class', w: ['Creating objects', 'Handling exceptions', 'Thread creation'], e: 'Child class extends parent class.', d: 'Easy' },
        { q: 'Polymorphism means?', c: 'Same method behaves differently based on context', w: ['One method one behavior', 'No methods', 'Static binding always'], e: 'Achieved via overloading and overriding.', d: 'Easy' },
        { q: 'Abstraction is implemented using?', c: 'Abstract classes and interfaces', w: ['Concrete classes only', 'Variables', 'Loops'], e: 'Hides implementation, shows only functionality.', d: 'Easy' },
        { q: 'Method overloading is?', c: 'Same method name with different parameters', w: ['Same name same parameters', 'Different classes', 'Different return type only'], e: 'Compile-time (static) polymorphism.', d: 'Easy' },
        { q: 'Method overriding is?', c: 'Child class redefines parent method with same signature', w: ['Different method name', 'Same class different params', 'Static methods'], e: 'Runtime (dynamic) polymorphism.', d: 'Easy' },
        { q: 'Constructor is called when?', c: 'Object is created using new keyword', w: ['Class is loaded', 'Method is called', 'Variable is declared'], e: 'Constructors initialize object state.', d: 'Easy' },
        { q: 'Interface in Java contains?', c: 'Abstract methods (and default/static in Java 8+)', w: ['Constructors', 'Instance variables', 'Main method'], e: 'Interface defines a contract for implementing classes.', d: 'Easy' },
        { q: 'ArrayList vs LinkedList: random access?', c: 'ArrayList is O(1), LinkedList is O(n)', w: ['Both O(1)', 'Both O(n)', 'LinkedList is faster'], e: 'ArrayList uses contiguous array; LinkedList traverses nodes.', d: 'Medium' },
        { q: 'HashMap allows?', c: 'One null key and multiple null values', w: ['No nulls', 'Multiple null keys', 'Only null values'], e: 'HashMap permits one null key in its implementation.', d: 'Medium' },
        { q: 'HashSet stores?', c: 'Unique elements only, no duplicates', w: ['Duplicates allowed', 'Key-value pairs', 'Sorted elements'], e: 'Internally uses HashMap; add returns false for duplicates.', d: 'Easy' },
        { q: 'TreeMap stores keys in?', c: 'Sorted (natural) order', w: ['Insertion order', 'Random order', 'Reverse order'], e: 'Red-black tree implementation maintains sorted keys.', d: 'Medium' },
        { q: 'PriorityQueue orders elements by?', c: 'Natural ordering or custom Comparator', w: ['Insertion order', 'Random', 'Alphabetical only'], e: 'Min-heap by default in Java.', d: 'Medium' },
        { q: 'try-catch-finally: finally block runs?', c: 'Always (except System.exit)', w: ['Only on exception', 'Only on success', 'Never'], e: 'Finally ensures cleanup code executes.', d: 'Easy' },
        { q: 'Checked exceptions are?', c: 'Verified at compile time', w: ['Runtime only', 'Never checked', 'OS-level errors'], e: 'Must be caught or declared with throws.', d: 'Medium' },
        { q: 'Custom exception extends?', c: 'Exception or RuntimeException', w: ['Object', 'String', 'Thread'], e: 'Custom exceptions inherit from exception hierarchy.', d: 'Medium' },
        { q: 'throw vs throws?', c: 'throw creates exception; throws declares it in method signature', w: ['Same thing', 'throw is for classes', 'throws catches exception'], e: 'throw is used in body; throws in declaration.', d: 'Medium' },
        { q: 'String is immutable in Java because?', c: 'Its value cannot be changed after creation', w: ['It uses char array', 'It is final class', 'It has no methods'], e: 'String pool and security require immutability.', d: 'Easy' },
        { q: 'StringBuilder vs StringBuffer?', c: 'StringBuilder is not thread-safe but faster', w: ['Both thread-safe', 'Both not thread-safe', 'StringBuffer is faster'], e: 'StringBuffer is synchronized; StringBuilder is not.', d: 'Medium' },
        { q: 'Thread can be created by?', c: 'Extending Thread class or implementing Runnable', w: ['Only extending Thread', 'Only Runnable', 'Using String class'], e: 'Two standard approaches to multithreading.', d: 'Easy' },
        { q: 'synchronized keyword ensures?', c: 'Only one thread accesses block/method at a time', w: ['All threads run simultaneously', 'Thread is stopped', 'Memory is freed'], e: 'Mutual exclusion for thread safety.', d: 'Medium' },
        { q: 'Executor framework provides?', c: 'Thread pool management', w: ['File handling', 'Database access', 'Network calls'], e: 'Manages thread lifecycle efficiently.', d: 'Medium' },
        { q: 'Lambda expression syntax?', c: '(parameters) -> expression/body', w: ['function(){}', 'def func():', 'method => param'], e: 'Java 8 functional programming feature.', d: 'Easy' },
        { q: 'Stream API is used for?', c: 'Functional-style operations on collections', w: ['File I/O streaming', 'Network streaming', 'Audio streaming'], e: 'map, filter, reduce operations on data.', d: 'Easy' },
        { q: 'Functional interface has?', c: 'Exactly one abstract method', w: ['Multiple abstract methods', 'No methods', 'Only default methods'], e: '@FunctionalInterface annotation enforces this.', d: 'Medium' },
        { q: 'Garbage collection in Java?', c: 'JVM automatically reclaims unused object memory', w: ['Programmer must free memory', 'OS handles it', 'No memory management'], e: 'GC runs in background; objects without references are collected.', d: 'Easy' },
        { q: 'Stack memory stores?', c: 'Method calls and local variables', w: ['Objects only', 'Static variables only', 'Class definitions'], e: 'Stack is LIFO; each thread has its own.', d: 'Medium' },
        { q: 'Heap memory stores?', c: 'Objects and instance variables', w: ['Local variables only', 'Method calls', 'Primitives only'], e: 'Shared heap stores dynamically allocated objects.', d: 'Medium' },
        { q: 'File class in Java represents?', c: 'File or directory path', w: ['File contents', 'Network socket', 'Database connection'], e: 'java.io.File for file system operations.', d: 'Easy' },
        { q: 'BufferedReader is faster than Scanner because?', c: 'Larger internal buffer reduces I/O operations', w: ['It skips characters', 'It uses less memory', 'It is newer'], e: 'BufferedReader reads large chunks at once.', d: 'Medium' },
        { q: 'Serialization converts object to?', c: 'Byte stream for storage or transmission', w: ['String format', 'XML only', 'HTML page'], e: 'Implements Serializable interface.', d: 'Medium' },
        { q: 'static keyword means?', c: 'Belongs to class, not instance', w: ['Belongs to instance', 'Cannot be accessed', 'Is private'], e: 'Static members shared across all instances.', d: 'Easy' },
        { q: 'final class cannot be?', c: 'Extended/inherited', w: ['Instantiated', 'Used', 'Imported'], e: 'final prevents subclassing.', d: 'Easy' },
        { q: 'abstract class can have?', c: 'Both abstract and concrete methods', w: ['Only abstract methods', 'Only concrete methods', 'No methods'], e: 'Abstract classes provide partial implementation.', d: 'Easy' },
        { q: 'this keyword refers to?', c: 'Current object instance', w: ['Parent class', 'Static context', 'Previous object'], e: 'this resolves ambiguity between fields and parameters.', d: 'Easy' },
        { q: 'super keyword is used to?', c: 'Call parent class constructor or method', w: ['Create new object', 'Handle exception', 'Define variable'], e: 'super() invokes parent constructor.', d: 'Easy' },
        { q: 'Dynamic method dispatch is?', c: 'Runtime resolution of overridden method call', w: ['Compile-time resolution', 'Static method call', 'Constructor call'], e: 'JVM determines which overridden method to call at runtime.', d: 'Hard' },
        { q: 'Optional class in Java 8 helps avoid?', c: 'NullPointerException', w: ['ArrayIndexOutOfBounds', 'StackOverflow', 'ClassCast'], e: 'Optional wraps nullable value with safe methods.', d: 'Medium' },
        { q: 'Comparator interface is used for?', c: 'Custom sorting logic', w: ['Equality checking', 'Hashing', 'Serialization'], e: 'compare() method defines custom ordering.', d: 'Medium' },
        { q: 'equals() vs == in Java?', c: 'equals() checks content equality; == checks reference', w: ['Both check reference', 'Both check content', 'No difference'], e: '== compares memory addresses for objects.', d: 'Easy' },
        { q: 'Autoboxing in Java is?', c: 'Automatic conversion of primitive to wrapper class', w: ['Manual casting', 'String to int', 'Object to primitive only'], e: 'int to Integer happens automatically.', d: 'Easy' },
        { q: 'Design pattern: Singleton ensures?', c: 'Only one instance of a class exists', w: ['Multiple instances', 'No instances', 'Abstract class'], e: 'Private constructor + static instance.', d: 'Medium' },
        { q: 'Design pattern: Factory provides?', c: 'Object creation without exposing instantiation logic', w: ['Sorting algorithm', 'Thread management', 'Memory allocation'], e: 'Factory method returns appropriate subclass instance.', d: 'Medium' },
        { q: 'Design pattern: Observer implements?', c: 'One-to-many dependency notification', w: ['Singleton pattern', 'Sorting', 'Tree traversal'], e: 'When subject changes, all observers are notified.', d: 'Hard' },
        { q: 'Design pattern: Builder is used for?', c: 'Constructing complex objects step by step', w: ['Destroying objects', 'Sorting', 'Threading'], e: 'Builder separates construction from representation.', d: 'Medium' },
        { q: 'What is classpath in Java?', c: 'Path where JVM looks for classes and packages', w: ['File system root', 'Network path', 'Database URL'], e: 'Set via -cp flag or CLASSPATH environment variable.', d: 'Medium' },
        { q: 'What is the default value of an int in Java?', c: '0', w: ['null', 'undefined', '-1'], e: 'Primitive int defaults to 0 in Java.', d: 'Easy' },
        { q: 'What is the default value of an Object reference?', c: 'null', w: ['0', 'undefined', 'empty string'], e: 'Uninitialized object references default to null.', d: 'Easy' },
        { q: 'Java supports multiple inheritance through?', c: 'Interfaces only', w: ['Classes', 'Abstract classes', 'Constructors'], e: 'Java avoids diamond problem by restricting class inheritance.', d: 'Medium' },
        { q: 'Enum in Java is?', c: 'A special class representing a fixed set of constants', w: ['A variable type', 'A method', 'A loop construct'], e: 'Enums provide type-safe constant definitions.', d: 'Easy' },
        { q: 'var keyword in Java 10+?', c: 'Local variable type inference', w: ['Global variable', 'Dynamic typing', 'Constant declaration'], e: 'Compiler infers type from initializer.', d: 'Medium' },
    ];
    items.forEach(it => all.push(Q(S, it.q.includes('OOP') || it.q.includes('ncapsulation') || it.q.includes('nheritance') || it.q.includes('olymorphism') || it.q.includes('bstraction') || it.q.includes('overload') || it.q.includes('overrid') || it.q.includes('nterface') ? 'OOP' : it.q.includes('tring') || it.q.includes('tringB') ? 'Strings' : it.q.includes('hread') || it.q.includes('ynchron') || it.q.includes('xecutor') ? 'Multithreading' : 'Java Core', it.d, it.q, it.c, it.w, it.e)));
    return all;
}

// ===================== OS =====================
function genOS() {
    const S = 'OS'; const all = [];
    const items = [
        { q: 'Process is?', c: 'Program in execution', w: ['Stored file', 'Hardware component', 'Static code'], e: 'Process = program + execution context.', d: 'Easy' },
        { q: 'Thread vs Process?', c: 'Thread shares process memory; process has own address space', w: ['Same thing', 'Thread is heavier', 'Process shares memory'], e: 'Threads are lightweight within a process.', d: 'Easy' },
        { q: 'PCB contains?', c: 'Process state, PID, registers, memory info', w: ['Only PID', 'Only memory', 'Only CPU info'], e: 'Process Control Block stores all process metadata.', d: 'Easy' },
        { q: 'Context switching involves?', c: 'Saving current process state and loading another', w: ['Deleting process', 'Creating new memory', 'Formatting disk'], e: 'OS saves/restores PCB during context switch.', d: 'Easy' },
        { q: 'FCFS scheduling is?', c: 'First Come First Served — non-preemptive', w: ['Preemptive', 'Priority-based', 'Random'], e: 'Processes executed in arrival order.', d: 'Easy' },
        { q: 'SJF scheduling selects?', c: 'Process with shortest burst time', w: ['Longest burst', 'Highest priority', 'Random'], e: 'Minimizes average waiting time (optimal for non-preemptive).', d: 'Easy' },
        { q: 'Round Robin uses?', c: 'Time quantum for preemption', w: ['Priority only', 'Burst time', 'No preemption'], e: 'Each process gets equal CPU time slice.', d: 'Easy' },
        { q: 'Priority scheduling risk?', c: 'Starvation of low-priority processes', w: ['Deadlock always', 'Too fast execution', 'Memory overflow'], e: 'Aging technique prevents starvation.', d: 'Medium' },
        { q: 'Semaphore is?', c: 'Integer variable for process synchronization', w: ['Process ID', 'Memory address', 'File descriptor'], e: 'wait() decrements; signal() increments.', d: 'Easy' },
        { q: 'Mutex is?', c: 'Binary semaphore for mutual exclusion', w: ['Counting semaphore', 'File lock', 'Memory segment'], e: 'Only owner thread can release mutex.', d: 'Easy' },
        { q: 'Deadlock conditions (all four)?', c: 'Mutual exclusion, Hold & wait, No preemption, Circular wait', w: ['Only mutual exclusion', 'Only circular wait', 'Only hold and wait'], e: 'All four Coffman conditions must hold simultaneously.', d: 'Medium' },
        { q: 'Banker\'s algorithm is for?', c: 'Deadlock avoidance', w: ['Deadlock detection', 'Deadlock prevention', 'Deadlock recovery'], e: 'Checks safe state before granting resources.', d: 'Medium' },
        { q: 'Paging divides?', c: 'Logical memory into fixed-size pages', w: ['Physical memory into segments', 'Files into blocks', 'CPU into cores'], e: 'Pages map to frames in physical memory.', d: 'Easy' },
        { q: 'Segmentation divides memory by?', c: 'Logical segments (code, data, stack)', w: ['Fixed-size pages', 'Random blocks', 'Equal partitions'], e: 'Variable-size segments based on program structure.', d: 'Medium' },
        { q: 'Virtual memory allows?', c: 'Execution of processes larger than physical memory', w: ['Faster CPU', 'More RAM', 'Better graphics'], e: 'Uses disk as extension of RAM via demand paging.', d: 'Easy' },
        { q: 'Thrashing occurs when?', c: 'Excessive page faults slow system drastically', w: ['CPU is idle', 'Memory is empty', 'Disk is full'], e: 'Process spends more time paging than executing.', d: 'Medium' },
        { q: 'Page replacement algorithm LRU evicts?', c: 'Least Recently Used page', w: ['Most recently used', 'Random page', 'First loaded page'], e: 'LRU approximates optimal by tracking usage recency.', d: 'Medium' },
        { q: 'FIFO page replacement?', c: 'Evicts the oldest page in memory', w: ['Newest page', 'Most used page', 'Least used page'], e: 'Simple but can suffer Belady\'s anomaly.', d: 'Easy' },
        { q: 'Optimal page replacement?', c: 'Evicts page not used for longest future time', w: ['Oldest page', 'Random page', 'Most used page'], e: 'Theoretical best; requires future knowledge.', d: 'Medium' },
        { q: 'TLB (Translation Lookaside Buffer) is?', c: 'Cache for page table entries', w: ['Main memory', 'Disk cache', 'CPU register'], e: 'Speeds up virtual to physical address translation.', d: 'Medium' },
        { q: 'File allocation methods include?', c: 'Contiguous, Linked, Indexed', w: ['Only contiguous', 'Only linked', 'Only indexed'], e: 'Each has trade-offs in speed and fragmentation.', d: 'Easy' },
        { q: 'Inode stores?', c: 'File metadata (size, permissions, pointers)', w: ['File content only', 'User passwords', 'Network addresses'], e: 'Unix/Linux inode contains all file attributes except name.', d: 'Medium' },
        { q: 'Disk scheduling SCAN (elevator)?', c: 'Moves in one direction then reverses', w: ['Random access', 'Always starts from 0', 'Shortest seek first'], e: 'Like an elevator, services requests in one direction.', d: 'Medium' },
        { q: 'SSTF disk scheduling?', c: 'Shortest Seek Time First', w: ['Random order', 'FIFO', 'Reverse order'], e: 'Services nearest request; can cause starvation of far requests.', d: 'Medium' },
        { q: 'System call is?', c: 'Interface between user program and OS kernel', w: ['Hardware interrupt', 'Software bug', 'Network protocol'], e: 'Programs request OS services via system calls.', d: 'Easy' },
        { q: 'fork() system call creates?', c: 'A new child process', w: ['New thread', 'New file', 'New device'], e: 'Child is copy of parent process.', d: 'Easy' },
        { q: 'Producer-Consumer problem uses?', c: 'Semaphores or mutex with bounded buffer', w: ['Sorting', 'File I/O only', 'CPU scheduling'], e: 'Classic synchronization problem with shared buffer.', d: 'Medium' },
        { q: 'Dining Philosophers problem illustrates?', c: 'Deadlock and synchronization challenges', w: ['Sorting efficiency', 'Memory allocation', 'File systems'], e: 'Five philosophers, five forks, potential circular wait.', d: 'Hard' },
        { q: 'Readers-Writers problem addresses?', c: 'Concurrent access to shared data', w: ['File compression', 'CPU scheduling', 'Memory allocation'], e: 'Multiple readers OK; writers need exclusive access.', d: 'Hard' },
        { q: 'Internal fragmentation occurs in?', c: 'Fixed-size allocation (paging)', w: ['Variable-size allocation', 'No allocation', 'Stack memory'], e: 'Allocated block larger than needed; wasted space within.', d: 'Medium' },
        { q: 'External fragmentation occurs in?', c: 'Variable-size allocation (segmentation)', w: ['Fixed-size allocation', 'Cache memory', 'CPU registers'], e: 'Enough total free memory but not contiguous.', d: 'Medium' },
        { q: 'Demand paging loads pages?', c: 'Only when they are accessed (on demand)', w: ['All at program start', 'Randomly', 'In sorted order'], e: 'Lazy loading reduces initial memory usage.', d: 'Easy' },
        { q: 'Working Set Model tracks?', c: 'Set of pages a process is currently using', w: ['All system pages', 'Disk blocks', 'CPU instructions'], e: 'Helps determine how many frames a process needs.', d: 'Hard' },
        { q: 'Belady\'s Anomaly?', c: 'More frames can cause more page faults in FIFO', w: ['Fewer frames always worse', 'LRU anomaly', 'Optimal anomaly'], e: 'Counter-intuitive: more memory can degrade FIFO performance.', d: 'Hard' },
        { q: 'Multithreading model: many-to-one?', c: 'Many user threads map to one kernel thread', w: ['One-to-one', 'Many-to-many', 'One-to-many'], e: 'Efficient but one block stops all.', d: 'Medium' },
        { q: 'Multithreading model: one-to-one?', c: 'Each user thread maps to one kernel thread', w: ['Many-to-one', 'Many-to-many', 'None'], e: 'More concurrency but higher overhead.', d: 'Medium' },
        { q: 'Starvation vs Deadlock?', c: 'Starvation: indefinite wait; Deadlock: permanent block', w: ['Same thing', 'Starvation is worse', 'Deadlock is temporary'], e: 'Starvation can be resolved; deadlock requires intervention.', d: 'Medium' },
        { q: 'Monitor is?', c: 'High-level synchronization construct with mutual exclusion', w: ['Hardware device', 'Network monitor', 'Disk management tool'], e: 'Encapsulates shared data with synchronized procedures.', d: 'Hard' },
        { q: 'Spooling is?', c: 'Simultaneous Peripheral Operation On-Line', w: ['Memory management', 'CPU scheduling', 'Network protocol'], e: 'Buffers data for slow devices like printers.', d: 'Medium' },
    ];
    items.forEach(it => all.push(Q(S, 'OS', it.d, it.q, it.c, it.w, it.e)));
    return all;
}

module.exports = { genAIML, genJava, genOS };
